### ISSUE TITLE
Feature request: generate QR from marked text

### ISSUE THREAD

**Issue by thenktor** [fnkr/chrome-qrcode-extension#1]
Hi,

it would be nice if a QR code could be generated from marked text inside the webside, e.g. mark a parcel tracking number on a website and scan it with a parcel tracking app on the phone.

**Comment by beatfreaker** [comment]
Made a pull request for the issue. currently updated the code such that it will generate QR Code for selected text if found any in current active tab or else it will follow the same thing to generate QR Code for the current active tab's URL.Let me know if you find this promising or not.

**Comment by thenktor** [comment]
Sounds good to me :+1:

**Comment by fnkr** [comment]
Fixed in v0.3.0. Chrome webstore may needs up to 60 minutes until its live.
